### ISSUE TITLE
PostgresCollection implementation is vulnerable to SQLi

### ISSUE THREAD

**Issue by avinashkolluru** [hypertrace/document-store#14]
See the method parseQueryForNonCompositeFilter here - https://github.com/hypertrace/document-store/blob/f9a3b6882e239b0d05b000e9db6744b268510adb/document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java#L207

We seem to be appending strings to create a SQL statement instead of creating a parameterized query using `?` and later setting the corresponding arguments while querying.

This is prone to SQL injection.

**Comment by JBAhire** [comment]
This has been addressed by #30 so closing this issue.
