### ISSUE TITLE
Provides supports for contains, exists and not_exists filter in postgres

### ISSUE THREAD

**Issue by kotharironak** [hypertrace/document-store#19]
Document store is exposing the following filters for query interface - https://github.com/hypertrace/document-store/blob/main/document-store/src/main/java/org/hypertrace/core/documentstore/Filter.java

Postgres implementation should also consider support for 'contains', 'exists' and 'not_exists' filter.
Recently, these filters are also exposed as part of entity-service - https://github.com/hypertrace/entity-service/pull/62.

**Comment by suresh-prakash** [comment]
Support added in https://github.com/hypertrace/document-store/pull/151
