### ISSUE TITLE
PreparedStatement preparedStatement may cause memory leakage.

### ISSUE THREAD

**Issue by afthabvp** [hypertrace/document-store#21]
[https://github.com/hypertrace/document-store/blob/main/document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java](url)
[https://github.com/hypertrace/document-store/blob/main/document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresDatastore.java](url)
**PreparedStatement preparedStatement**  should be close in finally block or use try-with-resources.

**Comment by jcchavezs** [comment]
Thank you! Are you up for a PR on this? Otherwise we will fix it soon.

**Comment by afthabvp** [comment]
@jcchavezs yeah, Is any access permission required to push the branch?

**Comment by jcchavezs** [comment]
Usual flow is that you fork the repo and open a PR against main.

**Comment by afthabvp** [comment]
Thank you @jcchavezs

**Comment by kotharironak** [comment]
@afthabvp I think, this PR - https://github.com/hypertrace/document-store/pull/23 - address this?

**Comment by kotharironak** [comment]
Closing this as PR has been merged and part of releases.
