### ISSUE TITLE
Support projections in Postgres

### ISSUE THREAD

**Issue by skjindal93** [hypertrace/document-store#29]
Document Store query interface https://github.com/hypertrace/document-store/blob/main/document-store/src/main/java/org/hypertrace/core/documentstore/Query.java can now support projections (selections)

The projections support has been added for Mongo recently https://github.com/hypertrace/document-store/pull/28

Add a similar support for projections for Postgres

**Comment by suresh-prakash** [comment]
Done in https://github.com/hypertrace/document-store/pull/95
