### ISSUE TITLE
Collection.updateSubDoc differs in behaviour between Postgres and mongodb implementation

### ISSUE THREAD

**Issue by utk-spartan** [hypertrace/document-store#34]
For initial document
`{"key1": "val1"}`

For keys with single level of nesting both have same behaviour
_mongoCollection.updateSubDoc("subdoc",  {"key2": "val2"})_
`{"key1": "val1", "subdoc": {"key2":"val2"}}`

_postgresCollection.updateSubDoc("subdoc",  {"key2": "val2"})_
`{"key1": "val1", "subdoc":  {"key2":"val2"}}`

But for multiple nesting when keys do not exist, both exhibit different behaviour
_mongoCollection.updateSubDoc("subdoc.nestedkey",  {"key2": "val2"})_
`{"key1": "val1", "subdoc": {"nestedkey": {"key2":"val2"}}}`
whereas
_postgresCollection.updateSubDoc("subdoc.nestedkey",  {"key2": "val2"})_
will do nothing
`{"key1": "val1"}`

This is due to to 
https://github.com/hypertrace/document-store/blob/e936b35faee99817bd40e86f32fb099d96ac973f/document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java#L128
_jsonb_set()_ only works if the object exists.

## Proposal
_jsonb_set()_ only works if object exists
whereas _jsonb_insert()_ only works if object does not exist.

The above code can be modified to generate following statement
```
UPDATE collectionName SET
document= (CASE
        WHEN document->'subdoc' IS NOT NULL
        THEN jsonb_set(document, '{subdoc,nestedkey}', '{"key2":val2}'::jsonb)
        WHEN document->'subdoc' IS NULL
        THEN jsonb_insert(document, '{subdoc}', '{"nestedkey":{"key2":val2}}'::jsonb)
    END)
WHERE id = ;
```
The above will bring parity between both mongo and postgres implementation.

## Questions

1. Should this method be renamed to upsertSubDoc ??
2. Currently updateSubDoc is only referenced from tests (based on github search). Is this used anywhere?

**Comment by suresh-prakash** [comment]
@utk-spartan The latest `update` and `bulkUpdate` methods are fully-compatible. 
Can you please check if it suits your use-case?
