### ISSUE TITLE
[Feature Request] Add API for bulk update with conditions 

### ISSUE THREAD

**Issue by surajpuvvada** [hypertrace/document-store#48]
## Use Case
*We have a background task that needs to flush updates periodically to the DB. This API will help us achieve that. *

## Proposal
API:
public boolean bulkUpdate(List<Triple<Key, Document, Filter>> documents);
The Filter can be used for specifying any conditions

**Comment by suresh-prakash** [comment]
Support added in https://github.com/hypertrace/document-store/pull/144
