### ISSUE TITLE
[Feature Request] Support the new find() and aggregate() operations for Postgres

### ISSUE THREAD

**Issue by suresh-prakash** [hypertrace/document-store#61]
## Use Case
The PR https://github.com/hypertrace/document-store/pull/59 introduced 2 new methods find() and aggregate() whose implementation is currently unsupported for Postgres. 

## Proposal
Implement the new methods in Postgres to support "GROUP BY" and "HAVING" clauses in addition to supporting mathematical operations.

**Comment by kotharironak** [comment]
This issue - https://github.com/hypertrace/document-store/issues/82 takes care of Postgres implementation. Closing this one.
