### ISSUE TITLE
Supporting new APIs for postgres implementation

### ISSUE THREAD

**Issue by kotharironak** [hypertrace/document-store#82]
Recently, there are 4 new APIs were added in document store:

- [x] Aggregate

     - CloseableIterator<Document> aggregate(final org.hypertrace.core.documentstore.query.Query query)

- [x]  Find

    - CloseableIterator<Document> find(final org.hypertrace.core.documentstore.query.Query query)

- [x] count
    - long count(final org.hypertrace.core.documentstore.query.Query query)

- [x] Bulk Operation On Array Value 

   - BulkUpdateResult bulkOperationOnArrayValue(BulkArrayValueUpdateRequest request) throws Exception

- [x] Bulk Update

  - BulkUpdateResult bulkUpdate(List<BulkUpdateRequest> bulkUpdateRequests) throws Exception

For the above APIs, we have implementation for MongoDB, however, we are lacking its support for Postgres. Can we add the support the support?

**Comment by suddendust** [comment]
@kotharironak `count` is already implemented?

**Comment by kotharironak** [comment]
Will take separately bugs + optimization tickets, closing this one.
